import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MasterBank - O banco que mais cresce no mundo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.banner}>
          <div className="container">
            <h1 className="text-center">Nós vamos mudar a sua vida</h1>
            <h3 className="text-center">Você está preparado?</h3>
          </div>
        </div>


        <section className="py-5 mb-5 mt-5" id="about" style={{ background: "#f2f2f2" }}>
          <div className="container">
            <h1 className="text-center">Conheca nossa história</h1>
            <p className="text-center" style={{ color: "#696666" }}>Somos o banco que mais cresce em todo o mundo</p>
            <div className="d-flex justify-content-center mt-4">


              <div className="w-50" style={{ marginRight: "24px" }}>
                <p style={{ color: "#696666" }} className="text-center">
                  A nossa história começa em 1875, quando o navegador Sir James Cook fundou o MasterBank na Inglaterra, após retornar de uma expedição às Américas.

                </p>

                <p style={{ color: "#696666" }} className="text-center">
                  Somos um banco que conhece os seus clientes e sabe como ajudá-los. Temos o know-how em investimentos e uma longa história de sucesso. Estamos prontos para ajudar você.
                  Seja bem vindo ao MasterBank.

                </p>

                <div className="d-flex justify-content-center mt-4">
                  <img src="/assets/images/logo2.png" alt="" width={200} />
                </div>

              </div>
            </div>

          </div>

        </section>

        <div className="row d-flex align-items-center p-5">
          <div className="col-sm">
            <img
              alt=""
              src="https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
              className="w-100"
              style={{ borderRadius: "8px", boxShadow: "5px 8px 30px 5px #c4c4c4" }}
            />
          </div>

          <div className="col-sm" style={{ marginLeft: "32px" }}>
            <h1 className="w-75 mt-4">Nós sabemos que podemos fazer a diferença na sua vida financeira</h1>

            <button className="btn btn-dark mt-4">Saiba mais</button>
          </div>
        </div>

    

        <section style={{ background: "#f2f2f2" }} id="services" className="py-5">
          <div className="container" >
            <h1 className="text-center">Nossos serviços</h1>
            <p className="text-center" style={{ color: "#696666" }}>Oferecemos as melhores vantagens para você</p>

            <div className="row">

              <ServiceCard
                title={"Conta digital exclusiva"}
                description={"Nossa conta oferece os últimos recursos para você não se preocupar com seu dinheiro"}
                icon={<i style={{ fontSize: "64px" }} className="fas fa-mobile-alt"></i>}
              />

              <ServiceCard
                title={"Investimentos personalizado"}
                description={"Nosso time de especialistas irá te ajudar a fazer seu dinheiro render"}
                icon={<i style={{ fontSize: "54px" }} className="fas fa-coins"></i>}
              />

              <ServiceCard
                title={"Cartão de crédito MasterBank"}
                description={"Cartão com varios benefícios incluindo crédtio ilimitado"}
                icon={<i style={{ fontSize: "45px" }} className="fas fa-money-check-alt"></i>}
              />

              <ServiceCard
                title={"Recarga de celular"}
                description={"Recarregue seu celular com a gente e ganhe bônus exclusivos"}
                icon={<i style={{ fontSize: "64px" }} className="fas fa-phone-alt"></i>}
              />

              <ServiceCard
                title={"Tranferências com pix"}
                description={"Faça transferências ilimitadas sem nenhuma pagar nenhuma taxa"}
                icon={<i style={{ fontSize: "54px" }} className="fas fa-comments-dollar"></i>}
              />

              <ServiceCard
                title={"Realize empréstimos"}
                description={"Consiga empréstimos para realizar o seu sonho"}
                icon={<i style={{ fontSize: "45px" }} className="fas fa-landmark"></i>}
              />




            </div>

          </div>
        </section>

        <section id="contact">
          <div className="container py-5">
            <h1 className="text-center">Entre em contato</h1>
            <p className="text-center" style={{ color: "#696666" }}>Vamos tirar todas as suas dúvidas</p>

            <div>
              <form>
                <div className="form-group mb-3">
                  <label htmlFor="exampleFormControlInput1">Seu nome</label>
                  <input type="text" className="form-control" id="exampleFormControlInput1" placeholder="Mark Joseph" />
                </div>

                <div className="form-group mb-3">
                  <label htmlFor="exampleFormControlInput1">Seu email</label>
                  <input type="email" className="form-control" id="exampleFormControlInput1" placeholder="name@example.com" />
                </div>


                <div className="form-group">
                  <label htmlFor="exampleFormControlTextarea1">Mensagem</label>
                  <textarea className="form-control" id="exampleFormControlTextarea1" rows={3} defaultValue={""} />
                </div>
                <div className="d-flex justify-content-end">
                  <button className="btn btn-dark mt-5">Enviar</button>
                </div>

              </form>

            </div>
          </div>
        </section>



      </main>

    </div>
  )
}


function ServiceCard({ title, description, icon }) {
  return (
    <div className="col-md-4 mt-4">
      <div className={styles.service_card}>
        <div
          style={{ width: "100px", height: "100px", background: "#e6eeff", borderRadius: "50vw" }}
          className="d-flex justify-content-center align-items-center p-3 mb-3">
          {icon}
        </div>
        <h3 className="text-center">{title}</h3>
        <span className="text-center">{description}</span>
      </div>
    </div>
  );
}
