import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div className={styles.banner}>
            <div>
              <h1>Nós vamos mudar a sua vida</h1>
              <h3>Você está preparado?</h3>
            </div>
          </div>

          <div className={styles.feature}>
            <img
              alt=""
              src="https://images.pexels.com/photos/4968391/pexels-photo-4968391.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
              />
              <div>
                <h1>Nós sabemos que podemos fazer a diferença na sua vida financeira</h1>
                {/* <h6 className="mt-3">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis ante ac tellus euismod, sit amet iaculis risus ultrices
                </h6> */}
                <button className="btn btn-dark mt-5">Saiba mais</button>
              </div>
          </div>

          <div className={styles.feature}>
            <img
              alt=""
              src="https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
              />
              <div>
                <h1>Nós vamos cuidar do seu dinheiro pra você</h1>
                {/* <h6 className="text-justify mt-3">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mattis ante ac tellus euismod, sit amet iaculis risus ultrices. Aliquam dui risus, ornare in scelerisque faucibus, elementum nec mi. Sed non sapien purus. Donec ut ultrices ligula, in lacinia ipsum. Morbi id mauris urna. In vestibulum dolor tellus. 
                </h6> */}
                <button className="btn btn-dark mt-5">Saiba mais</button>
              </div>
          </div>

          <div className="mt-5 mb-5 position-relative" style={{
            backgroundImage: "url(https://images.pexels.com/photos/9067435/pexels-photo-9067435.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940)",
            backgroundSize: "100%",
            backgroundRepeat: "no-repeat",
            width: "100%",
            height: "100vh"
            }}>
            <h1 className="text-left position-absolute"
              style={{
                top: "50%",
                left: "100px",
                width:"30%",
              }}
            >Tudo que você precisa na palma da sua mão</h1>
            {/* <img 
              alt=""
              src="https://images.pexels.com/photos/9067435/pexels-photo-9067435.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
              className="w-100"
            /> */}
          </div>

   

      </main>

    </div>
  )
}
